# Generated by Django 4.2.2 on 2023-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click the link above to read the blogs....', max_length=250),
        ),
    ]
